name: Build, Test and Publish

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - run: dotnet restore BrazilianDocs.sln
      - run: dotnet build BrazilianDocs.sln --configuration Release --no-restore
      - run: dotnet test tests/BrazilianDocs.Tests/BrazilianDocs.Tests.csproj --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"

  pack:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - run: dotnet pack src/BrazilianDocs/BrazilianDocs.csproj --configuration Release --no-build --output ./artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - uses: actions/download-artifact@v5
        with:
          name: nuget-package
          path: ./artifacts
      - run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
